/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aiAdoptionSidebar: [
    {
      type: 'category',
      label: '🚀 AI 導入 AIA',
      link: {type: 'generated-index', description: 'AI 導入研究與 AIA 切入方案'},
      items: [{type: 'autogenerated', dirName: 'ai-adoption'}],
    },
  ],
  tutorialSidebar: [
    {
      type: 'category',
      label: '🔧 Google Workspace',
      link: {type: 'generated-index', description: 'Google 服務整合案例'},
      items: [{type: 'autogenerated', dirName: 'google-workspace'}],
    },
    {
      type: 'category',
      label: '📡 資訊查詢',
      link: {type: 'generated-index', description: '資訊查詢與摘要案例'},
      items: [{type: 'autogenerated', dirName: 'information'}],
    },
    {
      type: 'category',
      label: '⚡ 自動化',
      link: {type: 'generated-index', description: '自動化與排程任務案例'},
      items: [{type: 'autogenerated', dirName: 'automation'}],
    },
    {
      type: 'category',
      label: '💬 通訊',
      link: {type: 'generated-index', description: '多平台溝通案例'},
      items: [{type: 'autogenerated', dirName: 'communication'}],
    },
    {
      type: 'category',
      label: '🎮 娛樂',
      link: {type: 'generated-index', description: '互動娛樂功能案例'},
      items: [{type: 'autogenerated', dirName: 'entertainment'}],
    },
  ],
};

module.exports = sidebars;
